version: "3"
services:
  web:
    container_name: web
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      - HOST_NAME=${HOST_NAME}
      - APP_PORT=${APP_PORT}
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - "80:80"
    depends_on:
      - app
      - api
    tty: true
  app:
    container_name: react_app
    privileged: true
    restart: always
    stdin_open: true
    tty: true
    command: /bin/sh
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - APP_PORT=${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./app/src:/usr/src/app
    depends_on:
      - api
  api:
    container_name: go_api
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - API_PORT=${API_PORT}
        - GO_VERSION=${GO_VERSION}
        - API_CODE_LOCAL_PATH=${API_CODE_LOCAL_PATH}
        - API_CODE_WORKDIR=${API_CODE_WORKDIR}
    volumes:
      - ${API_CODE_LOCAL_PATH}:${API_CODE_WORKDIR}
    ports:
      - ${API_PORT}:${API_PORT}
    tty: true
