version: "3"
services:
  web:
    container_name: web
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      - HOST_NAME=${HOST_NAME}
      - APP_PORT=${APP_PORT}
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - "80:80"
    depends_on:
      - app
      - api
    tty: true
  app:
    container_name: next_app
    build:
      context: ./task_maven_front
      dockerfile: Dockerfile
      args:
        - APP_PORT=${APP_PORT}
        - APP_WORKDIR=${APP_WORKDIR}
        - APP_LOCAL_PATH=${APP_LOCAL_PATH}
        - NODE_VER=${NODE_VER}
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ${APP_LOCAL_PATH}:${APP_WORKDIR}
      - node_modules:${APP_WORKDIR}/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    privileged: true
    stdin_open: true
    depends_on:
      - api
  api:
    container_name: go_api
    build:
      context: ./task_maven_back
      dockerfile: Dockerfile
      args:
        - API_PORT=${API_PORT}
        - API_LOCAL_PATH=${API_LOCAL_PATH}
        - API_WORKDIR=${API_WORKDIR}
    volumes:
      - ${API_LOCAL_PATH}:${API_WORKDIR}
    ports:
      - ${API_PORT}:${API_PORT}
    tty: true

volumes:
  node_modules:
